### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test Name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg4NDc0ODJ9.3a3v8NNdlxWloPuE2kJqbWezptx87NJNaf6xVzoIzjk

### Photos create
GET  
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}